CREATE TABLE IF NOT EXISTS `queue` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '自增 id',
	`namespace` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '命名空间',
	`url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '回调事件接口',
	`count` INT NOT NULL DEFAULT 0 COMMENT '队列支持的并发数量',
	`run_crontab` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '运行周期规则',
	`check_crontab` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '检查周期规则',
	`expire_crontab` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '过期周期规则',
	`created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '任务队列表';
